<?php
/*

// Our custom error handler
function nettuts_error_handler($number, $message)
{
    $email = "<p>An error ($number)</p><p> $message </p>";
         
	$defaultAdminEmailAddress = 'dmitrij@seopro.lt';
	$headers  = 'MIME-Version: 1.0' . "\r\n";
	$headers .= 'Content-type: text/html; charset=UTF-8' . "\r\n";
	$headers .= 'From: '.$defaultAdminEmailAddress . "\r\n" .
	'Reply-To: '.$defaultAdminEmailAddress . "\r\n" .
	'X-Mailer: PHP/' . phpversion();
      
    // Email the error to someone...
    error_log($email, 1, $defaultAdminEmailAddress, $headers);
}
set_error_handler('nettuts_error_handler');
*/
require_once __DIR__ . '/google-api-php-client-2.2.1/checkIP.php';
//if (($thisIp == '79.142.123.81') || ($thisIp == '79.98.30.99')){
require_once __DIR__ . '/google-api-php-client-2.2.1/HelloAnalytics2.php';

//membershop.lt
//require_once __DIR__ .'/membershop.lt/mysql-config.php';
//require_once __DIR__ .'/membershop.lt/mysql-TEST_1.1_orig.php';
//require_once __DIR__ .'/membershop.lt/mysql-TEST_1.1_var1.php';
//require_once __DIR__ .'/membershop.lt/mysql-TEST_11.1_orig.php';
//equire_once __DIR__ .'/membershop.lt/mysql-TEST_11.1_var1.php';
//require_once __DIR__ .'/membershop.lt/mysql-TEST_12_orig.php';
//require_once __DIR__ .'/membershop.lt/mysql-TEST_12_var1.php';
//require_once __DIR__ .'/membershop.lt/mysql-TEST_13_orig.php';
//require_once __DIR__ .'/membershop.lt/mysql-TEST_13_var1.php';
//require_once __DIR__ .'/membershop.lt/mysql-TEST_14_orig.php';
//require_once __DIR__ .'/membershop.lt/mysql-TEST_14_var1.php';
//require_once __DIR__ .'/membershop.lt/mysql-TEST_15_orig.php';
//require_once __DIR__ .'/membershop.lt/mysql-TEST_15_var1.php';
//require_once __DIR__ .'/membershop.lt/mysql-TEST_16_orig.php';
//require_once __DIR__ .'/membershop.lt/mysql-TEST_16_var1.php';
//require_once __DIR__ .'/membershop.lt/mysql-TEST_17_orig.php';
//require_once __DIR__ .'/membershop.lt/mysql-TEST_17_var1.php';
//require_once __DIR__ .'/membershop.lt/mysql-TEST_18_orig.php';
//require_once __DIR__ .'/membershop.lt/mysql-TEST_18_var1.php';
//require_once __DIR__ .'/membershop.lt/mysql-TEST_19_orig.php';
//require_once __DIR__ .'/membershop.lt/mysql-TEST_19_var1.php';
//require_once __DIR__ .'/membershop.lt/mysql-TEST_20_orig.php';
//require_once __DIR__ .'/membershop.lt/mysql-TEST_20_var1.php';
//require_once __DIR__ .'/membershop.lt/mysql-TEST_22_orig.php';
//require_once __DIR__ .'/membershop.lt/mysql-TEST_22_var1.php';
//require_once __DIR__ .'/membershop.lt/mysql-TEST_23_orig.php';
//require_once __DIR__ .'/membershop.lt/mysql-TEST_23_var1.php';
//require_once __DIR__ .'/membershop.lt/mysql-TEST_24_orig.php';
//require_once __DIR__ .'/membershop.lt/mysql-TEST_24_var1.php';
//require_once __DIR__ .'/membershop.lt/mysql-TEST_25_orig.php';
//require_once __DIR__ .'/membershop.lt/mysql-TEST_25_var1.php';
//require_once __DIR__ .'/membershop.lt/mysql-TEST_26_orig.php';
//require_once __DIR__ .'/membershop.lt/mysql-TEST_26_var1.php';
//require_once __DIR__ .'/membershop.lt/mysql-TEST_27_orig.php';
//require_once __DIR__ .'/membershop.lt/mysql-TEST_27_var1.php';
//require_once __DIR__ .'/membershop.lt/mysql-TEST_28_orig.php';
//require_once __DIR__ .'/membershop.lt/mysql-TEST_28_var1.php';
//require_once __DIR__ .'/membershop.lt/mysql-TEST_29_orig.php';
//require_once __DIR__ .'/membershop.lt/mysql-TEST_29_var1.php';
//require_once __DIR__ .'/membershop.lt/mysql-TEST_30_orig.php';
//require_once __DIR__ .'/membershop.lt/mysql-TEST_30_var1.php';
//require_once __DIR__ .'/membershop.lt/mysql-TEST_31_orig.php';
//require_once __DIR__ .'/membershop.lt/mysql-TEST_31_var1.php';
//require_once __DIR__ .'/membershop.lt/mysql-TEST_32_orig.php';
//require_once __DIR__ .'/membershop.lt/mysql-TEST_32_var1.php';
//require_once __DIR__ .'/membershop.lt/mysql-TEST_33_orig.php';
//require_once __DIR__ .'/membershop.lt/mysql-TEST_33_var1.php';
//require_once __DIR__ .'/membershop.lt/mysql-TEST_allSessions.php';

//membershop.ee
//require_once __DIR__ .'/membershop.ee/mysql-config.php';
//require_once __DIR__ .'/membershop.ee/mysql-TEST_13_orig.php';
//require_once __DIR__ .'/membershop.ee/mysql-TEST_13_var1.php';
//require_once __DIR__ .'/membershop.ee/mysql-TEST_14_orig.php';
//require_once __DIR__ .'/membershop.ee/mysql-TEST_14_var1.php';
//require_once __DIR__ .'/membershop.ee/mysql-TEST_15_orig.php';
//require_once __DIR__ .'/membershop.ee/mysql-TEST_15_var1.php';
//require_once __DIR__ .'/membershop.ee/mysql-TEST_16_orig.php';
//require_once __DIR__ .'/membershop.ee/mysql-TEST_16_var1.php';
//require_once __DIR__ .'/membershop.ee/mysql-TEST_17_orig.php';
//require_once __DIR__ .'/membershop.ee/mysql-TEST_17_var1.php';
//require_once __DIR__ .'/membershop.ee/mysql-TEST_18_orig.php';
//require_once __DIR__ .'/membershop.ee/mysql-TEST_18_var1.php';
//require_once __DIR__ .'/membershop.ee/mysql-TEST_19_orig.php';
//require_once __DIR__ .'/membershop.ee/mysql-TEST_19_var1.php';
//require_once __DIR__ .'/membershop.ee/mysql-TEST_20_orig.php';
//require_once __DIR__ .'/membershop.ee/mysql-TEST_20_var1.php';
//require_once __DIR__ .'/membershop.ee/mysql-TEST_21_orig.php';
//require_once __DIR__ .'/membershop.ee/mysql-TEST_21_var1.php';
//require_once __DIR__ .'/membershop.ee/mysql-TEST_allSessions.php';

//membershop.lv
//require_once __DIR__ .'/membershop.lv/mysql-config.php';
//require_once __DIR__ .'/membershop.lv/mysql-TEST_13_orig.php';
//require_once __DIR__ .'/membershop.lv/mysql-TEST_13_var1.php';
//require_once __DIR__ .'/membershop.lv/mysql-TEST_14_orig.php';
//require_once __DIR__ .'/membershop.lv/mysql-TEST_14_var1.php';
//require_once __DIR__ .'/membershop.lv/mysql-TEST_15_orig.php';
//require_once __DIR__ .'/membershop.lv/mysql-TEST_15_var1.php';
//require_once __DIR__ .'/membershop.lv/mysql-TEST_16_orig.php';
//require_once __DIR__ .'/membershop.lv/mysql-TEST_16_var1.php';
//require_once __DIR__ .'/membershop.lv/mysql-TEST_17_orig.php';
//require_once __DIR__ .'/membershop.lv/mysql-TEST_17_var1.php';
//require_once __DIR__ .'/membershop.lv/mysql-TEST_18_orig.php';
//require_once __DIR__ .'/membershop.lv/mysql-TEST_18_var1.php';
//require_once __DIR__ .'/membershop.lv/mysql-TEST_19_orig.php';
//require_once __DIR__ .'/membershop.lv/mysql-TEST_19_var1.php';
//require_once __DIR__ .'/membershop.lv/mysql-TEST_20_orig.php';
//require_once __DIR__ .'/membershop.lv/mysql-TEST_20_var1.php';
//require_once __DIR__ .'/membershop.lv/mysql-TEST_21_orig.php';
//require_once __DIR__ .'/membershop.lv/mysql-TEST_21_var1.php';
//require_once __DIR__ .'/membershop.lv/mysql-TEST_allSessions.php';

//pigu.lt
require_once __DIR__ .'/pigu.lt/mysql-config.php';
//require_once __DIR__ .'/pigu.lt/mysql-TEST_21_orig.php';
//require_once __DIR__ .'/pigu.lt/mysql-TEST_21_var1.php';
//require_once __DIR__ .'/pigu.lt/mysql-TEST_22_orig.php';
//require_once __DIR__ .'/pigu.lt/mysql-TEST_22_var1.php';
//require_once __DIR__ .'/pigu.lt/mysql-TEST_23_orig.php';
//require_once __DIR__ .'/pigu.lt/mysql-TEST_23_var1.php';
//require_once __DIR__ .'/pigu.lt/mysql-TEST_24_orig.php';
//require_once __DIR__ .'/pigu.lt/mysql-TEST_24_var1.php';
//require_once __DIR__ .'/pigu.lt/mysql-TEST_25_orig.php';
//require_once __DIR__ .'/pigu.lt/mysql-TEST_25_var1.php';
//require_once __DIR__ .'/pigu.lt/mysql-TEST_26_orig.php';
//require_once __DIR__ .'/pigu.lt/mysql-TEST_26_var1.php';
//require_once __DIR__ .'/pigu.lt/mysql-TEST_27_orig.php';
//require_once __DIR__ .'/pigu.lt/mysql-TEST_27_var1.php';
//require_once __DIR__ .'/pigu.lt/mysql-TEST_28_orig.php';
//require_once __DIR__ .'/pigu.lt/mysql-TEST_28_var1.php';
//require_once __DIR__ .'/pigu.lt/mysql-TEST_29_orig.php';
//require_once __DIR__ .'/pigu.lt/mysql-TEST_29_var1.php';
//require_once __DIR__ .'/pigu.lt/mysql-TEST_30_orig.php';
//require_once __DIR__ .'/pigu.lt/mysql-TEST_30_var1.php';
//require_once __DIR__ .'/pigu.lt/mysql-TEST_31_orig.php';
//require_once __DIR__ .'/pigu.lt/mysql-TEST_31_var1.php';
//require_once __DIR__ .'/pigu.lt/mysql-TEST_32_orig.php';
//require_once __DIR__ .'/pigu.lt/mysql-TEST_32_var1.php';
//require_once __DIR__ .'/pigu.lt/mysql-TEST_34_orig.php';
//require_once __DIR__ .'/pigu.lt/mysql-TEST_34_var1.php';
//require_once __DIR__ .'/pigu.lt/mysql-TEST_35_orig.php';
//require_once __DIR__ .'/pigu.lt/mysql-TEST_35_var1.php';
//require_once __DIR__ .'/pigu.lt/mysql-TEST_36_orig.php';
//require_once __DIR__ .'/pigu.lt/mysql-TEST_36_var1.php';
//require_once __DIR__ .'/pigu.lt/mysql-TEST_37_orig.php';
//require_once __DIR__ .'/pigu.lt/mysql-TEST_37_var1.php';
//require_once __DIR__ .'/pigu.lt/mysql-TEST_38_orig.php';
//require_once __DIR__ .'/pigu.lt/mysql-TEST_38_var1.php';
//require_once __DIR__ .'/pigu.lt/mysql-TEST_39_orig.php';
//require_once __DIR__ .'/pigu.lt/mysql-TEST_39_var1.php';
//require_once __DIR__ .'/pigu.lt/mysql-TEST_40_orig.php';
//require_once __DIR__ .'/pigu.lt/mysql-TEST_40_var1.php';
//require_once __DIR__ .'/pigu.lt/mysql-TEST_41_orig.php';
//require_once __DIR__ .'/pigu.lt/mysql-TEST_41_var1.php';
//require_once __DIR__ .'/pigu.lt/mysql-TEST_42_orig.php';
//require_once __DIR__ .'/pigu.lt/mysql-TEST_42_var1.php';
//require_once __DIR__ .'/pigu.lt/mysql-TEST_43_orig.php';
//require_once __DIR__ .'/pigu.lt/mysql-TEST_43_var1.php';
//require_once __DIR__ .'/pigu.lt/mysql-TEST_44_orig.php';
//require_once __DIR__ .'/pigu.lt/mysql-TEST_44_var1.php';
//require_once __DIR__ .'/pigu.lt/mysql-TEST_45_orig.php';
//require_once __DIR__ .'/pigu.lt/mysql-TEST_45_var1.php';
//require_once __DIR__ .'/pigu.lt/mysql-TEST_46_orig.php';
//require_once __DIR__ .'/pigu.lt/mysql-TEST_46_var1.php';
//require_once __DIR__ .'/pigu.lt/mysql-TEST_47_orig.php';
//require_once __DIR__ .'/pigu.lt/mysql-TEST_47_var1.php';
//require_once __DIR__ .'/pigu.lt/mysql-TEST_48_orig.php';
//require_once __DIR__ .'/pigu.lt/mysql-TEST_48_var1.php';
//require_once __DIR__ .'/pigu.lt/mysql-TEST_49_orig.php';
//require_once __DIR__ .'/pigu.lt/mysql-TEST_49_var1.php';
//require_once __DIR__ .'/pigu.lt/mysql-TEST_50_orig.php';
//require_once __DIR__ .'/pigu.lt/mysql-TEST_50_var1.php';
//require_once __DIR__ .'/pigu.lt/mysql-TEST_51_orig.php';
//require_once __DIR__ .'/pigu.lt/mysql-TEST_51_var1.php';
//require_once __DIR__ .'/pigu.lt/mysql-TEST_52_orig.php';
//require_once __DIR__ .'/pigu.lt/mysql-TEST_52_var1.php';
//require_once __DIR__ .'/pigu.lt/mysql-TEST_53_orig.php';
//require_once __DIR__ .'/pigu.lt/mysql-TEST_53_var1.php';
//require_once __DIR__ .'/pigu.lt/mysql-TEST_54_orig.php';
//require_once __DIR__ .'/pigu.lt/mysql-TEST_54_var1.php';
//require_once __DIR__ .'/pigu.lt/mysql-TEST_55_orig.php';
//require_once __DIR__ .'/pigu.lt/mysql-TEST_55_var1.php';
//require_once __DIR__ .'/pigu.lt/mysql-TEST_56_orig.php';
//require_once __DIR__ .'/pigu.lt/mysql-TEST_56_var1.php';
//require_once __DIR__ .'/pigu.lt/mysql-TEST_58_orig.php';
//require_once __DIR__ .'/pigu.lt/mysql-TEST_58_var1.php';
//require_once __DIR__ .'/pigu.lt/mysql-TEST_59_orig.php';
//require_once __DIR__ .'/pigu.lt/mysql-TEST_59_var1.php';
//require_once __DIR__ .'/pigu.lt/mysql-TEST_60_orig.php';
//require_once __DIR__ .'/pigu.lt/mysql-TEST_60_var1.php';
//require_once __DIR__ .'/pigu.lt/mysql-TEST_61_orig.php';
//require_once __DIR__ .'/pigu.lt/mysql-TEST_61_var1.php';
require_once __DIR__ .'/pigu.lt/mysql-TEST_allSessions.php';

//kaup24.ee
require_once __DIR__ .'/kaup24.ee/mysql-config.php';
//require_once __DIR__ .'/kaup24.ee/mysql-TEST_21_orig.php';
//require_once __DIR__ .'/kaup24.ee/mysql-TEST_21_var1.php';
//require_once __DIR__ .'/kaup24.ee/mysql-TEST_22_orig.php';
//require_once __DIR__ .'/kaup24.ee/mysql-TEST_22_var1.php';
//require_once __DIR__ .'/kaup24.ee/mysql-TEST_23_orig.php';
//require_once __DIR__ .'/kaup24.ee/mysql-TEST_23_var1.php';
//require_once __DIR__ .'/kaup24.ee/mysql-TEST_24_orig.php';
//require_once __DIR__ .'/kaup24.ee/mysql-TEST_24_var1.php';
//require_once __DIR__ .'/kaup24.ee/mysql-TEST_25_orig.php';
//require_once __DIR__ .'/kaup24.ee/mysql-TEST_25_var1.php';
//require_once __DIR__ .'/kaup24.ee/mysql-TEST_26_orig.php';
//require_once __DIR__ .'/kaup24.ee/mysql-TEST_26_var1.php';
//require_once __DIR__ .'/kaup24.ee/mysql-TEST_27_orig.php';
//require_once __DIR__ .'/kaup24.ee/mysql-TEST_27_var1.php';
//require_once __DIR__ .'/kaup24.ee/mysql-TEST_29_orig.php';
//require_once __DIR__ .'/kaup24.ee/mysql-TEST_29_var1.php';
//require_once __DIR__ .'/kaup24.ee/mysql-TEST_30_orig.php';
//require_once __DIR__ .'/kaup24.ee/mysql-TEST_30_var1.php';
//require_once __DIR__ .'/kaup24.ee/mysql-TEST_31_orig.php';
//require_once __DIR__ .'/kaup24.ee/mysql-TEST_31_var1.php';
//require_once __DIR__ .'/kaup24.ee/mysql-TEST_32_orig.php';
//require_once __DIR__ .'/kaup24.ee/mysql-TEST_32_var1.php';
//require_once __DIR__ .'/kaup24.ee/mysql-TEST_34_orig.php';
//require_once __DIR__ .'/kaup24.ee/mysql-TEST_34_var1.php';
//require_once __DIR__ .'/kaup24.ee/mysql-TEST_35_orig.php';
//require_once __DIR__ .'/kaup24.ee/mysql-TEST_35_var1.php';
require_once __DIR__ .'/kaup24.ee/mysql-TEST_allSessions.php';

//220.lv
require_once __DIR__ .'/220.lv/mysql-config.php';
//require_once __DIR__ .'/220.lv/mysql-TEST_21_orig.php';
//require_once __DIR__ .'/220.lv/mysql-TEST_21_var1.php';
//require_once __DIR__ .'/220.lv/mysql-TEST_22_orig.php';
//require_once __DIR__ .'/220.lv/mysql-TEST_22_var1.php';
//require_once __DIR__ .'/220.lv/mysql-TEST_23_orig.php';
//require_once __DIR__ .'/220.lv/mysql-TEST_23_var1.php';
//require_once __DIR__ .'/220.lv/mysql-TEST_24_orig.php';
//require_once __DIR__ .'/220.lv/mysql-TEST_24_var1.php';
//require_once __DIR__ .'/220.lv/mysql-TEST_26_orig.php';
//require_once __DIR__ .'/220.lv/mysql-TEST_26_var1.php';
//require_once __DIR__ .'/220.lv/mysql-TEST_27_orig.php';
//require_once __DIR__ .'/220.lv/mysql-TEST_27_var1.php';
//require_once __DIR__ .'/220.lv/mysql-TEST_29_orig.php';
//require_once __DIR__ .'/220.lv/mysql-TEST_29_var1.php';
//require_once __DIR__ .'/220.lv/mysql-TEST_30_orig.php';
//require_once __DIR__ .'/220.lv/mysql-TEST_30_var1.php';
//require_once __DIR__ .'/220.lv/mysql-TEST_31_orig.php';
//require_once __DIR__ .'/220.lv/mysql-TEST_31_var1.php';
//require_once __DIR__ .'/220.lv/mysql-TEST_32_orig.php';
//require_once __DIR__ .'/220.lv/mysql-TEST_32_var1.php';
//require_once __DIR__ .'/220.lv/mysql-TEST_34_orig.php';
//require_once __DIR__ .'/220.lv/mysql-TEST_34_var1.php';
//require_once __DIR__ .'/220.lv/mysql-TEST_35_orig.php';
//require_once __DIR__ .'/220.lv/mysql-TEST_35_var1.php';
require_once __DIR__ .'/220.lv/mysql-TEST_allSessions.php';

//novaturas.lt
/*
require_once __DIR__ .'/novaturas.lt/mysql-config.php';
require_once __DIR__ .'/novaturas.lt/mysql-TEST_4_orig.php';
require_once __DIR__ .'/novaturas.lt/mysql-TEST_4_var1.php';
require_once __DIR__ .'/novaturas.lt/mysql-TEST_allSessions.php';
*/
//newmood.lt
//require_once __DIR__ .'/newmood.lt/mysql-config.php';
//require_once __DIR__ .'/newmood.lt/mysql-TEST_1_orig.php';
//require_once __DIR__ .'/newmood.lt/mysql-TEST_1_var1.php';
//require_once __DIR__ .'/newmood.lt/mysql-TEST_2_orig.php';
//require_once __DIR__ .'/newmood.lt/mysql-TEST_2_var1.php';
//require_once __DIR__ .'/newmood.lt/mysql-TEST_3_orig.php';
//require_once __DIR__ .'/newmood.lt/mysql-TEST_3_var1.php';
//require_once __DIR__ .'/newmood.lt/mysql-TEST_4_orig.php';
//require_once __DIR__ .'/newmood.lt/mysql-TEST_4_var1.php';
//require_once __DIR__ .'/newmood.lt/mysql-TEST_5_orig.php';
//require_once __DIR__ .'/newmood.lt/mysql-TEST_5_var1.php';
//require_once __DIR__ .'/newmood.lt/mysql-TEST_6_orig.php';
//require_once __DIR__ .'/newmood.lt/mysql-TEST_6_var1.php';
//require_once __DIR__ .'/newmood.lt/mysql-TEST_7_orig.php';
//require_once __DIR__ .'/newmood.lt/mysql-TEST_7_var1.php';
//require_once __DIR__ .'/newmood.lt/mysql-TEST_8_orig.php';
//require_once __DIR__ .'/newmood.lt/mysql-TEST_8_var1.php';
//require_once __DIR__ .'/newmood.lt/mysql-TEST_9_orig.php';
//require_once __DIR__ .'/newmood.lt/mysql-TEST_9_var1.php';
//require_once __DIR__ .'/newmood.lt/mysql-TEST_allSessions.php';

//newmood.ee
//require_once __DIR__ .'/newmood.ee/mysql-config.php';
//require_once __DIR__ .'/newmood.ee/mysql-TEST_1_orig.php';
//require_once __DIR__ .'/newmood.ee/mysql-TEST_1_var1.php';
//require_once __DIR__ .'/newmood.ee/mysql-TEST_2_orig.php';
//require_once __DIR__ .'/newmood.ee/mysql-TEST_2_var1.php';
//require_once __DIR__ .'/newmood.ee/mysql-TEST_3_orig.php';
//require_once __DIR__ .'/newmood.ee/mysql-TEST_3_var1.php';
//require_once __DIR__ .'/newmood.ee/mysql-TEST_4_orig.php';
//require_once __DIR__ .'/newmood.ee/mysql-TEST_4_var1.php';
//require_once __DIR__ .'/newmood.ee/mysql-TEST_5_orig.php';
//require_once __DIR__ .'/newmood.ee/mysql-TEST_5_var1.php';
//require_once __DIR__ .'/newmood.ee/mysql-TEST_6_orig.php';
//require_once __DIR__ .'/newmood.ee/mysql-TEST_6_var1.php';
//require_once __DIR__ .'/newmood.ee/mysql-TEST_7_orig.php';
//require_once __DIR__ .'/newmood.ee/mysql-TEST_7_var1.php';
//require_once __DIR__ .'/newmood.ee/mysql-TEST_8_orig.php';
//require_once __DIR__ .'/newmood.ee/mysql-TEST_8_var1.php';
//require_once __DIR__ .'/newmood.ee/mysql-TEST_9_orig.php';
//require_once __DIR__ .'/newmood.ee/mysql-TEST_9_var1.php';
//require_once __DIR__ .'/newmood.ee/mysql-TEST_allSessions.php';

//newmood.lv
//require_once __DIR__ .'/newmood.lv/mysql-config.php';
//require_once __DIR__ .'/newmood.lv/mysql-TEST_1_orig.php';
//require_once __DIR__ .'/newmood.lv/mysql-TEST_1_var1.php';
//require_once __DIR__ .'/newmood.lv/mysql-TEST_2_orig.php';
//require_once __DIR__ .'/newmood.lv/mysql-TEST_2_var1.php';
//require_once __DIR__ .'/newmood.lv/mysql-TEST_3_orig.php';
//require_once __DIR__ .'/newmood.lv/mysql-TEST_3_var1.php';
//require_once __DIR__ .'/newmood.lv/mysql-TEST_4_orig.php';
//require_once __DIR__ .'/newmood.lv/mysql-TEST_4_var1.php';
//require_once __DIR__ .'/newmood.lv/mysql-TEST_5_orig.php';
//require_once __DIR__ .'/newmood.lv/mysql-TEST_5_var1.php';
//require_once __DIR__ .'/newmood.lv/mysql-TEST_6_orig.php';
//require_once __DIR__ .'/newmood.lv/mysql-TEST_6_var1.php';
//require_once __DIR__ .'/newmood.lv/mysql-TEST_7_orig.php';
//require_once __DIR__ .'/newmood.lv/mysql-TEST_7_var1.php';
//require_once __DIR__ .'/newmood.lv/mysql-TEST_8_orig.php';
//require_once __DIR__ .'/newmood.lv/mysql-TEST_8_var1.php';
//require_once __DIR__ .'/newmood.lv/mysql-TEST_9_orig.php';
//require_once __DIR__ .'/newmood.lv/mysql-TEST_9_var1.php';
//require_once __DIR__ .'/newmood.lv/mysql-TEST_allSessions.php';

//babycity.lt
require_once __DIR__ .'/babycity.lt/mysql-config.php';
//require_once __DIR__ .'/babycity.lt/mysql-TEST_1_orig.php';
//require_once __DIR__ .'/babycity.lt/mysql-TEST_1_var1.php';
//require_once __DIR__ .'/babycity.lt/mysql-TEST_2_orig.php';
//require_once __DIR__ .'/babycity.lt/mysql-TEST_2_var1.php';
//require_once __DIR__ .'/babycity.lt/mysql-TEST_3_orig.php';
//require_once __DIR__ .'/babycity.lt/mysql-TEST_3_var1.php';
//require_once __DIR__ .'/babycity.lt/mysql-TEST_4_orig.php';
//require_once __DIR__ .'/babycity.lt/mysql-TEST_4_var1.php';
//require_once __DIR__ .'/babycity.lt/mysql-TEST_5_orig.php';
//require_once __DIR__ .'/babycity.lt/mysql-TEST_5_var1.php';
//require_once __DIR__ .'/babycity.lt/mysql-TEST_6_orig.php';
//require_once __DIR__ .'/babycity.lt/mysql-TEST_6_var1.php';
//require_once __DIR__ .'/babycity.lt/mysql-TEST_8_orig.php';
//require_once __DIR__ .'/babycity.lt/mysql-TEST_8_var1.php';
//require_once __DIR__ .'/babycity.lt/mysql-TEST_9_orig.php';
//require_once __DIR__ .'/babycity.lt/mysql-TEST_9_var1.php';
//require_once __DIR__ .'/babycity.lt/mysql-TEST_10_orig.php';
//require_once __DIR__ .'/babycity.lt/mysql-TEST_10_var1.php';
//require_once __DIR__ .'/babycity.lt/mysql-TEST_11_orig.php';
//require_once __DIR__ .'/babycity.lt/mysql-TEST_11_var1.php';
//require_once __DIR__ .'/babycity.lt/mysql-TEST_12_orig.php';
//require_once __DIR__ .'/babycity.lt/mysql-TEST_12_var1.php';
//require_once __DIR__ .'/babycity.lt/mysql-TEST_13_orig.php';
//require_once __DIR__ .'/babycity.lt/mysql-TEST_13_var1.php';
//require_once __DIR__ .'/babycity.lt/mysql-TEST_14_orig.php';
//require_once __DIR__ .'/babycity.lt/mysql-TEST_14_var1.php';
//require_once __DIR__ .'/babycity.lt/mysql-TEST_15_orig.php';
//require_once __DIR__ .'/babycity.lt/mysql-TEST_15_var1.php';
//require_once __DIR__ .'/babycity.lt/mysql-TEST_16_orig.php';
//require_once __DIR__ .'/babycity.lt/mysql-TEST_16_var1.php';
require_once __DIR__ .'/babycity.lt/mysql-TEST_allSessions.php';

//toycity.lt
require_once __DIR__ .'/toycity.lt/mysql-config.php';
//require_once __DIR__ .'/toycity.lt/mysql-TEST_1_orig.php';
//require_once __DIR__ .'/toycity.lt/mysql-TEST_1_var1.php';
//require_once __DIR__ .'/toycity.lt/mysql-TEST_2_orig.php';
//require_once __DIR__ .'/toycity.lt/mysql-TEST_2_var1.php';
//require_once __DIR__ .'/toycity.lt/mysql-TEST_3_orig.php';
//require_once __DIR__ .'/toycity.lt/mysql-TEST_3_var1.php';
//require_once __DIR__ .'/toycity.lt/mysql-TEST_4_orig.php';
//require_once __DIR__ .'/toycity.lt/mysql-TEST_4_var1.php';
//require_once __DIR__ .'/toycity.lt/mysql-TEST_6_orig.php';
//require_once __DIR__ .'/toycity.lt/mysql-TEST_6_var1.php';
//require_once __DIR__ .'/toycity.lt/mysql-TEST_8_orig.php';
//require_once __DIR__ .'/toycity.lt/mysql-TEST_8_var1.php';
//require_once __DIR__ .'/toycity.lt/mysql-TEST_9_orig.php';
//require_once __DIR__ .'/toycity.lt/mysql-TEST_9_var1.php';
//require_once __DIR__ .'/toycity.lt/mysql-TEST_10_orig.php';
//require_once __DIR__ .'/toycity.lt/mysql-TEST_10_var1.php';
//require_once __DIR__ .'/toycity.lt/mysql-TEST_11_orig.php';
//require_once __DIR__ .'/toycity.lt/mysql-TEST_11_var1.php';
require_once __DIR__ .'/toycity.lt/mysql-TEST_allSessions.php';

//jukukeskus.ee
require_once __DIR__ .'/jukukeskus.ee/mysql-config.php';
//require_once __DIR__ .'/jukukeskus.ee/mysql-TEST_1_orig.php';
//require_once __DIR__ .'/jukukeskus.ee/mysql-TEST_1_var1.php';
//require_once __DIR__ .'/jukukeskus.ee/mysql-TEST_2_orig.php';
//require_once __DIR__ .'/jukukeskus.ee/mysql-TEST_2_var1.php';
//require_once __DIR__ .'/jukukeskus.ee/mysql-TEST_3_orig.php';
//require_once __DIR__ .'/jukukeskus.ee/mysql-TEST_3_var1.php';
//require_once __DIR__ .'/jukukeskus.ee/mysql-TEST_4_orig.php';
//require_once __DIR__ .'/jukukeskus.ee/mysql-TEST_4_var1.php';
//require_once __DIR__ .'/jukukeskus.ee/mysql-TEST_5_orig.php';
//require_once __DIR__ .'/jukukeskus.ee/mysql-TEST_5_var1.php';
//require_once __DIR__ .'/jukukeskus.ee/mysql-TEST_6_orig.php';
//require_once __DIR__ .'/jukukeskus.ee/mysql-TEST_6_var1.php';
//require_once __DIR__ .'/jukukeskus.ee/mysql-TEST_7_orig.php';
//require_once __DIR__ .'/jukukeskus.ee/mysql-TEST_7_var1.php';
require_once __DIR__ .'/jukukeskus.ee/mysql-TEST_allSessions.php';

//medcentras.lt
require_once __DIR__ .'/medcentras.lt/mysql-config.php';
//require_once __DIR__ .'/medcentras.lt/mysql-TEST_1_orig.php';
//require_once __DIR__ .'/medcentras.lt/mysql-TEST_1_var1.php';
//require_once __DIR__ .'/medcentras.lt/mysql-TEST_2_orig.php';
//require_once __DIR__ .'/medcentras.lt/mysql-TEST_2_var1.php';
//require_once __DIR__ .'/medcentras.lt/mysql-TEST_3_orig.php';
//require_once __DIR__ .'/medcentras.lt/mysql-TEST_3_var1.php';
//require_once __DIR__ .'/medcentras.lt/mysql-TEST_4_orig.php';
//require_once __DIR__ .'/medcentras.lt/mysql-TEST_4_var1.php';
//require_once __DIR__ .'/medcentras.lt/mysql-TEST_5_orig.php';
//require_once __DIR__ .'/medcentras.lt/mysql-TEST_5_var1.php';
//require_once __DIR__ .'/medcentras.lt/mysql-TEST_6_orig.php';
//require_once __DIR__ .'/medcentras.lt/mysql-TEST_6_var1.php';
//require_once __DIR__ .'/medcentras.lt/mysql-TEST_7_orig.php';
//require_once __DIR__ .'/medcentras.lt/mysql-TEST_7_var1.php';
//require_once __DIR__ .'/medcentras.lt/mysql-TEST_8_orig.php';
//require_once __DIR__ .'/medcentras.lt/mysql-TEST_8_var1.php';
//require_once __DIR__ .'/medcentras.lt/mysql-TEST_9_orig.php';
//require_once __DIR__ .'/medcentras.lt/mysql-TEST_9_var1.php';
//require_once __DIR__ .'/medcentras.lt/mysql-TEST_10_orig.php';
//require_once __DIR__ .'/medcentras.lt/mysql-TEST_10_var1.php';
//require_once __DIR__ .'/medcentras.lt/mysql-TEST_11_orig.php';
//require_once __DIR__ .'/medcentras.lt/mysql-TEST_11_var1.php';
//require_once __DIR__ .'/medcentras.lt/mysql-TEST_12_orig.php';
//require_once __DIR__ .'/medcentras.lt/mysql-TEST_12_var1.php';
//require_once __DIR__ .'/medcentras.lt/mysql-TEST_13_orig.php';
//require_once __DIR__ .'/medcentras.lt/mysql-TEST_13_var1.php';
//require_once __DIR__ .'/medcentras.lt/mysql-TEST_14_orig.php';
//require_once __DIR__ .'/medcentras.lt/mysql-TEST_14_var1.php';
//require_once __DIR__ .'/medcentras.lt/mysql-TEST_15_orig.php';
//require_once __DIR__ .'/medcentras.lt/mysql-TEST_15_var1.php';
//require_once __DIR__ .'/medcentras.lt/mysql-TEST_16_orig.php';
//require_once __DIR__ .'/medcentras.lt/mysql-TEST_16_var1.php';
//require_once __DIR__ .'/medcentras.lt/mysql-TEST_17_orig.php';
//require_once __DIR__ .'/medcentras.lt/mysql-TEST_17_var1.php';
//require_once __DIR__ .'/medcentras.lt/mysql-TEST_18_orig.php';
//require_once __DIR__ .'/medcentras.lt/mysql-TEST_18_var1.php';
//require_once __DIR__ .'/medcentras.lt/mysql-TEST_19_orig.php';
//require_once __DIR__ .'/medcentras.lt/mysql-TEST_19_var1.php';
require_once __DIR__ .'/medcentras.lt/mysql-TEST_allSessions.php';

//elektromarkt.lt
//require_once __DIR__ .'/elektromarkt.lt/mysql-config.php';
//require_once __DIR__ .'/elektromarkt.lt/mysql-TEST_1_orig.php';
//require_once __DIR__ .'/elektromarkt.lt/mysql-TEST_1_var1.php';
//require_once __DIR__ .'/elektromarkt.lt/mysql-TEST_2_orig.php';
//require_once __DIR__ .'/elektromarkt.lt/mysql-TEST_2_var1.php';
//require_once __DIR__ .'/elektromarkt.lt/mysql-TEST_3_orig.php';
//require_once __DIR__ .'/elektromarkt.lt/mysql-TEST_3_var1.php';
//require_once __DIR__ .'/elektromarkt.lt/mysql-TEST_5_orig.php';
//require_once __DIR__ .'/elektromarkt.lt/mysql-TEST_5_var1.php';
//require_once __DIR__ .'/elektromarkt.lt/mysql-TEST_6_orig.php';
//require_once __DIR__ .'/elektromarkt.lt/mysql-TEST_6_var1.php';
//require_once __DIR__ .'/elektromarkt.lt/mysql-TEST_7_orig.php';
//require_once __DIR__ .'/elektromarkt.lt/mysql-TEST_7_var1.php';
//require_once __DIR__ .'/elektromarkt.lt/mysql-TEST_9_orig.php';
//require_once __DIR__ .'/elektromarkt.lt/mysql-TEST_9_var1.php';
//require_once __DIR__ .'/elektromarkt.lt/mysql-TEST_11_orig.php';
//require_once __DIR__ .'/elektromarkt.lt/mysql-TEST_11_var1.php';
//require_once __DIR__ .'/elektromarkt.lt/mysql-TEST_aa_orig.php';
//require_once __DIR__ .'/elektromarkt.lt/mysql-TEST_aa_var1.php';
//require_once __DIR__ .'/elektromarkt.lt/mysql-TEST_allSessions.php';

//laisvalaikiodovanos.lt
//require_once __DIR__ .'/laisvalaikiodovanos.lt/mysql-config.php';
//require_once __DIR__ .'/laisvalaikiodovanos.lt/mysql-TEST_1_orig.php';
//require_once __DIR__ .'/laisvalaikiodovanos.lt/mysql-TEST_1_var1.php';
//require_once __DIR__ .'/laisvalaikiodovanos.lt/mysql-TEST_2_orig.php';
//require_once __DIR__ .'/laisvalaikiodovanos.lt/mysql-TEST_2_var1.php';
//require_once __DIR__ .'/laisvalaikiodovanos.lt/mysql-TEST_3_orig.php';
//require_once __DIR__ .'/laisvalaikiodovanos.lt/mysql-TEST_3_var1.php';
//require_once __DIR__ .'/laisvalaikiodovanos.lt/mysql-TEST_4_orig.php';
//require_once __DIR__ .'/laisvalaikiodovanos.lt/mysql-TEST_4_var1.php';
//require_once __DIR__ .'/laisvalaikiodovanos.lt/mysql-TEST_5_orig.php';
//require_once __DIR__ .'/laisvalaikiodovanos.lt/mysql-TEST_5_var1.php';
//require_once __DIR__ .'/laisvalaikiodovanos.lt/mysql-TEST_6_orig.php';
//require_once __DIR__ .'/laisvalaikiodovanos.lt/mysql-TEST_6_var1.php';
//require_once __DIR__ .'/laisvalaikiodovanos.lt/mysql-TEST_7_orig.php';
//require_once __DIR__ .'/laisvalaikiodovanos.lt/mysql-TEST_7_var1.php';
//require_once __DIR__ .'/laisvalaikiodovanos.lt/mysql-TEST_allSessions.php';
/*
//perlas.lt
require_once __DIR__ .'/perlas.lt/mysql-config.php';
require_once __DIR__ .'/perlas.lt/mysql-TEST_1_orig.php';
require_once __DIR__ .'/perlas.lt/mysql-TEST_1_var1.php';
require_once __DIR__ .'/perlas.lt/mysql-TEST_2_orig.php';
require_once __DIR__ .'/perlas.lt/mysql-TEST_2_var1.php';
require_once __DIR__ .'/perlas.lt/mysql-TEST_3_orig.php';
require_once __DIR__ .'/perlas.lt/mysql-TEST_3_var1.php';
require_once __DIR__ .'/perlas.lt/mysql-TEST_4_orig.php';
require_once __DIR__ .'/perlas.lt/mysql-TEST_4_var1.php';
require_once __DIR__ .'/perlas.lt/mysql-TEST_5_orig.php';
require_once __DIR__ .'/perlas.lt/mysql-TEST_5_var1.php';
//require_once __DIR__ .'/perlas.lt/mysql-TEST_8_orig.php';
//require_once __DIR__ .'/perlas.lt/mysql-TEST_8_var1.php';
require_once __DIR__ .'/perlas.lt/mysql-TEST_9_orig.php';
require_once __DIR__ .'/perlas.lt/mysql-TEST_9_var1.php';
require_once __DIR__ .'/perlas.lt/mysql-TEST_10_orig.php';
require_once __DIR__ .'/perlas.lt/mysql-TEST_10_var1.php';
require_once __DIR__ .'/perlas.lt/mysql-TEST_allSessions.php';
*/
//changex.com
//require_once __DIR__ .'/changex.com/mysql-config.php';
//require_once __DIR__ .'/changex.com/mysql-TEST_1_orig.php';
//require_once __DIR__ .'/changex.com/mysql-TEST_1_var1.php';
//require_once __DIR__ .'/changex.com/mysql-TEST_2_orig.php';
//require_once __DIR__ .'/changex.com/mysql-TEST_2_var1.php';
//require_once __DIR__ .'/changex.com/mysql-TEST_allSessions.php';

//cgtrader.com
//require_once __DIR__ .'/cgtrader.com/mysql-config.php';
//require_once __DIR__ .'/cgtrader.com/mysql-TEST_1_orig.php';
//require_once __DIR__ .'/cgtrader.com/mysql-TEST_1_var1.php';
//require_once __DIR__ .'/cgtrader.com/mysql-TEST_2_orig.php';
//require_once __DIR__ .'/cgtrader.com/mysql-TEST_2_var1.php';
//require_once __DIR__ .'/cgtrader.com/mysql-TEST_3_orig.php';
//require_once __DIR__ .'/cgtrader.com/mysql-TEST_3_var1.php';
//require_once __DIR__ .'/cgtrader.com/mysql-TEST_5_orig.php';
//require_once __DIR__ .'/cgtrader.com/mysql-TEST_5_var1.php';
//require_once __DIR__ .'/cgtrader.com/mysql-TEST_6_orig.php';
//require_once __DIR__ .'/cgtrader.com/mysql-TEST_6_var1.php';
//require_once __DIR__ .'/cgtrader.com/mysql-TEST_7_orig.php';
//require_once __DIR__ .'/cgtrader.com/mysql-TEST_7_var1.php';
//require_once __DIR__ .'/cgtrader.com/mysql-TEST_8_orig.php';
//require_once __DIR__ .'/cgtrader.com/mysql-TEST_8_var1.php';
//require_once __DIR__ .'/cgtrader.com/mysql-TEST_9_orig.php';
//require_once __DIR__ .'/cgtrader.com/mysql-TEST_9_var1.php';
//require_once __DIR__ .'/cgtrader.com/mysql-TEST_10_orig.php';
//require_once __DIR__ .'/cgtrader.com/mysql-TEST_10_var1.php';
//require_once __DIR__ .'/cgtrader.com/mysql-TEST_11_orig.php';
//require_once __DIR__ .'/cgtrader.com/mysql-TEST_11_var1.php';
//require_once __DIR__ .'/cgtrader.com/mysql-TEST_12_orig.php';
//require_once __DIR__ .'/cgtrader.com/mysql-TEST_12_var1.php';
//require_once __DIR__ .'/cgtrader.com/mysql-TEST_13_orig.php';
//require_once __DIR__ .'/cgtrader.com/mysql-TEST_13_var1.php';
//require_once __DIR__ .'/cgtrader.com/mysql-TEST_allSessions.php';

//barbora.lt
require_once __DIR__ .'/barbora.lt/mysql-config.php';
//require_once __DIR__ .'/barbora.lt/mysql-TEST_1_orig.php';
//require_once __DIR__ .'/barbora.lt/mysql-TEST_1_var1.php';
//require_once __DIR__ .'/barbora.lt/mysql-TEST_2_orig.php';
//require_once __DIR__ .'/barbora.lt/mysql-TEST_2_var1.php';
//require_once __DIR__ .'/barbora.lt/mysql-TEST_3_orig.php';
//require_once __DIR__ .'/barbora.lt/mysql-TEST_3_var1.php';
//require_once __DIR__ .'/barbora.lt/mysql-TEST_4_orig.php';
//require_once __DIR__ .'/barbora.lt/mysql-TEST_4_var1.php';
//require_once __DIR__ .'/barbora.lt/mysql-TEST_5_orig.php';
//require_once __DIR__ .'/barbora.lt/mysql-TEST_5_var1.php';
//require_once __DIR__ .'/barbora.lt/mysql-TEST_6_orig.php';
//require_once __DIR__ .'/barbora.lt/mysql-TEST_6_var1.php';
//require_once __DIR__ .'/barbora.lt/mysql-TEST_7_orig.php';
//require_once __DIR__ .'/barbora.lt/mysql-TEST_7_var1.php';
//require_once __DIR__ .'/barbora.lt/mysql-TEST_8_orig.php';
//require_once __DIR__ .'/barbora.lt/mysql-TEST_8_var1.php';
//require_once __DIR__ .'/barbora.lt/mysql-TEST_9_orig.php';
//require_once __DIR__ .'/barbora.lt/mysql-TEST_9_var1.php';
//require_once __DIR__ .'/barbora.lt/mysql-TEST_10_orig.php';
//require_once __DIR__ .'/barbora.lt/mysql-TEST_10_var1.php';
//require_once __DIR__ .'/barbora.lt/mysql-TEST_11_orig.php';
//require_once __DIR__ .'/barbora.lt/mysql-TEST_11_var1.php';
//require_once __DIR__ .'/barbora.lt/mysql-TEST_12_orig.php';
//require_once __DIR__ .'/barbora.lt/mysql-TEST_12_var1.php';
//require_once __DIR__ .'/barbora.lt/mysql-TEST_13_orig.php';
//require_once __DIR__ .'/barbora.lt/mysql-TEST_13_var1.php';
//require_once __DIR__ .'/barbora.lt/mysql-TEST_14_orig.php';
//require_once __DIR__ .'/barbora.lt/mysql-TEST_14_var1.php';
//require_once __DIR__ .'/barbora.lt/mysql-TEST_15_orig.php';
//require_once __DIR__ .'/barbora.lt/mysql-TEST_15_var1.php';
require_once __DIR__ .'/barbora.lt/mysql-TEST_aa_orig.php';
require_once __DIR__ .'/barbora.lt/mysql-TEST_aa_var1.php';
require_once __DIR__ .'/barbora.lt/mysql-TEST_allSessions.php';

//credit24.lt
require_once __DIR__ .'/credit24.lt/mysql-config.php';
//require_once __DIR__ .'/credit24.lt/mysql-TEST_1_orig.php';
//require_once __DIR__ .'/credit24.lt/mysql-TEST_1_var1.php';
//require_once __DIR__ .'/credit24.lt/mysql-TEST_2_orig.php';
//require_once __DIR__ .'/credit24.lt/mysql-TEST_2_var1.php';
//require_once __DIR__ .'/credit24.lt/mysql-TEST_3_orig.php';
//require_once __DIR__ .'/credit24.lt/mysql-TEST_3_var1.php';
//require_once __DIR__ .'/credit24.lt/mysql-TEST_4_orig.php';
//require_once __DIR__ .'/credit24.lt/mysql-TEST_4_var1.php';
//require_once __DIR__ .'/credit24.lt/mysql-TEST_5_orig.php';
//require_once __DIR__ .'/credit24.lt/mysql-TEST_5_var1.php';
//require_once __DIR__ .'/credit24.lt/mysql-TEST_6_orig.php';
//require_once __DIR__ .'/credit24.lt/mysql-TEST_6_var1.php';
//require_once __DIR__ .'/credit24.lt/mysql-TEST_7_orig.php';
//require_once __DIR__ .'/credit24.lt/mysql-TEST_7_var1.php';
//require_once __DIR__ .'/credit24.lt/mysql-TEST_8_orig.php';
//require_once __DIR__ .'/credit24.lt/mysql-TEST_8_var1.php';
//require_once __DIR__ .'/credit24.lt/mysql-TEST_9_orig.php';
//require_once __DIR__ .'/credit24.lt/mysql-TEST_9_var1.php';
//require_once __DIR__ .'/credit24.lt/mysql-TEST_10_orig.php';
//require_once __DIR__ .'/credit24.lt/mysql-TEST_10_var1.php';
//require_once __DIR__ .'/credit24.lt/mysql-TEST_11_orig.php';
//require_once __DIR__ .'/credit24.lt/mysql-TEST_11_var1.php';
//require_once __DIR__ .'/credit24.lt/mysql-TEST_12_orig.php';
//require_once __DIR__ .'/credit24.lt/mysql-TEST_12_var1.php';
//require_once __DIR__ .'/credit24.lt/mysql-TEST_13_orig.php';
//require_once __DIR__ .'/credit24.lt/mysql-TEST_13_var1.php';
//require_once __DIR__ .'/credit24.lt/mysql-TEST_14_orig.php';
//require_once __DIR__ .'/credit24.lt/mysql-TEST_14_var1.php';
//require_once __DIR__ .'/credit24.lt/mysql-TEST_15_orig.php';
//require_once __DIR__ .'/credit24.lt/mysql-TEST_15_var1.php';
//require_once __DIR__ .'/credit24.lt/mysql-TEST_16_orig.php';
//require_once __DIR__ .'/credit24.lt/mysql-TEST_16_var1.php';
//require_once __DIR__ .'/credit24.lt/mysql-TEST_17_orig.php';
//require_once __DIR__ .'/credit24.lt/mysql-TEST_17_var1.php';
//require_once __DIR__ .'/credit24.lt/mysql-TEST_18_orig.php';
//require_once __DIR__ .'/credit24.lt/mysql-TEST_18_var1.php';
//require_once __DIR__ .'/credit24.lt/mysql-TEST_19_orig.php';
//require_once __DIR__ .'/credit24.lt/mysql-TEST_19_var1.php';
//require_once __DIR__ .'/credit24.lt/mysql-TEST_20_orig.php';
//require_once __DIR__ .'/credit24.lt/mysql-TEST_20_var1.php';
//require_once __DIR__ .'/credit24.lt/mysql-TEST_21_orig.php';
//require_once __DIR__ .'/credit24.lt/mysql-TEST_21_var1.php';
//require_once __DIR__ .'/credit24.lt/mysql-TEST_22_orig.php';
//require_once __DIR__ .'/credit24.lt/mysql-TEST_22_var1.php';
//require_once __DIR__ .'/credit24.lt/mysql-TEST_24_orig.php';
//require_once __DIR__ .'/credit24.lt/mysql-TEST_24_var1.php';
//require_once __DIR__ .'/credit24.lt/mysql-TEST_26_orig.php';
//require_once __DIR__ .'/credit24.lt/mysql-TEST_26_var1.php';
//require_once __DIR__ .'/credit24.lt/mysql-TEST_27_orig.php';
//require_once __DIR__ .'/credit24.lt/mysql-TEST_27_var1.php';
//require_once __DIR__ .'/credit24.lt/mysql-TEST_28_orig.php';
//require_once __DIR__ .'/credit24.lt/mysql-TEST_28_var1.php';
//require_once __DIR__ .'/credit24.lt/mysql-TEST_29_orig.php';
//require_once __DIR__ .'/credit24.lt/mysql-TEST_29_var1.php';
//require_once __DIR__ .'/credit24.lt/mysql-TEST_30_orig.php';
//require_once __DIR__ .'/credit24.lt/mysql-TEST_30_var1.php';
//require_once __DIR__ .'/credit24.lt/mysql-TEST_31_orig.php';
//require_once __DIR__ .'/credit24.lt/mysql-TEST_31_var1.php';
//require_once __DIR__ .'/credit24.lt/mysql-TEST_32_orig.php';
//require_once __DIR__ .'/credit24.lt/mysql-TEST_32_var1.php';
//require_once __DIR__ .'/credit24.lt/mysql-TEST_33_orig.php';
//require_once __DIR__ .'/credit24.lt/mysql-TEST_33_var1.php';
//require_once __DIR__ .'/credit24.lt/mysql-TEST_34_orig.php';
//require_once __DIR__ .'/credit24.lt/mysql-TEST_34_var1.php';
//require_once __DIR__ .'/credit24.lt/mysql-TEST_35_orig.php';
//require_once __DIR__ .'/credit24.lt/mysql-TEST_35_var1.php';
//require_once __DIR__ .'/credit24.lt/mysql-TEST_36_orig.php';
//require_once __DIR__ .'/credit24.lt/mysql-TEST_36_var1.php';
//require_once __DIR__ .'/credit24.lt/mysql-TEST_37_orig.php';
//require_once __DIR__ .'/credit24.lt/mysql-TEST_37_var1.php';
//require_once __DIR__ .'/credit24.lt/mysql-TEST_38_orig.php';
//require_once __DIR__ .'/credit24.lt/mysql-TEST_38_var1.php';
//require_once __DIR__ .'/credit24.lt/mysql-TEST_39_orig.php';
//require_once __DIR__ .'/credit24.lt/mysql-TEST_39_var1.php';
//require_once __DIR__ .'/credit24.lt/mysql-TEST_40_orig.php';
//require_once __DIR__ .'/credit24.lt/mysql-TEST_40_var1.php';
//require_once __DIR__ .'/credit24.lt/mysql-TEST_41_orig.php';
//require_once __DIR__ .'/credit24.lt/mysql-TEST_41_var1.php';
//require_once __DIR__ .'/credit24.lt/mysql-TEST_42_orig.php';
//require_once __DIR__ .'/credit24.lt/mysql-TEST_42_var1.php';
//require_once __DIR__ .'/credit24.lt/mysql-TEST_43_orig.php';
//require_once __DIR__ .'/credit24.lt/mysql-TEST_43_var1.php';
require_once __DIR__ .'/credit24.lt/mysql-TEST_aa_orig.php';
require_once __DIR__ .'/credit24.lt/mysql-TEST_aa_var1.php';
require_once __DIR__ .'/credit24.lt/mysql-TEST_allSessions.php';

//niekorimto.lt
//require_once __DIR__ .'/niekorimto.lt/mysql-config.php';
//require_once __DIR__ .'/niekorimto.lt/mysql-TEST_1_orig.php';
//require_once __DIR__ .'/niekorimto.lt/mysql-TEST_1_var1.php';
//require_once __DIR__ .'/niekorimto.lt/mysql-TEST_2_orig.php';
//require_once __DIR__ .'/niekorimto.lt/mysql-TEST_2_var1.php';
//require_once __DIR__ .'/niekorimto.lt/mysql-TEST_3_orig.php';
//require_once __DIR__ .'/niekorimto.lt/mysql-TEST_3_var1.php';
//require_once __DIR__ .'/niekorimto.lt/mysql-TEST_4_orig.php';
//require_once __DIR__ .'/niekorimto.lt/mysql-TEST_4_var1.php';
//require_once __DIR__ .'/niekorimto.lt/mysql-TEST_5_orig.php';
//require_once __DIR__ .'/niekorimto.lt/mysql-TEST_5_var1.php';
//require_once __DIR__ .'/niekorimto.lt/mysql-TEST_6_orig.php';
//require_once __DIR__ .'/niekorimto.lt/mysql-TEST_6_var1.php';
//require_once __DIR__ .'/niekorimto.lt/mysql-TEST_7_orig.php';
//require_once __DIR__ .'/niekorimto.lt/mysql-TEST_7_var1.php';
//require_once __DIR__ .'/niekorimto.lt/mysql-TEST_8_orig.php';
//require_once __DIR__ .'/niekorimto.lt/mysql-TEST_8_var1.php';
//require_once __DIR__ .'/niekorimto.lt/mysql-TEST_9_orig.php';
//require_once __DIR__ .'/niekorimto.lt/mysql-TEST_9_var1.php';
//require_once __DIR__ .'/niekorimto.lt/mysql-TEST_aa_orig.php';
//require_once __DIR__ .'/niekorimto.lt/mysql-TEST_aa_var1.php';
//require_once __DIR__ .'/niekorimto.lt/mysql-TEST_allSessions.php';

//apie-iqos.lt
require_once __DIR__ .'/apie-iqos.lt/mysql-config.php';
//require_once __DIR__ .'/apie-iqos.lt/mysql-TEST_1_orig.php';
//require_once __DIR__ .'/apie-iqos.lt/mysql-TEST_1_var1.php';
//require_once __DIR__ .'/apie-iqos.lt/mysql-TEST_allSessions.php';

//extremeiceland.is
require_once __DIR__ .'/extremeiceland.is/mysql-config.php';
//require_once __DIR__ .'/extremeiceland.is/mysql-TEST_1_orig.php';
//require_once __DIR__ .'/extremeiceland.is/mysql-TEST_1_var1.php';
//require_once __DIR__ .'/extremeiceland.is/mysql-TEST_2_orig.php';
//require_once __DIR__ .'/extremeiceland.is/mysql-TEST_2_var1.php';
//require_once __DIR__ .'/extremeiceland.is/mysql-TEST_3_orig.php';
//require_once __DIR__ .'/extremeiceland.is/mysql-TEST_3_var1.php';
//require_once __DIR__ .'/extremeiceland.is/mysql-TEST_4_orig.php';
//require_once __DIR__ .'/extremeiceland.is/mysql-TEST_4_var1.php';
//require_once __DIR__ .'/extremeiceland.is/mysql-TEST_5_orig.php';
//require_once __DIR__ .'/extremeiceland.is/mysql-TEST_5_var1.php';
//require_once __DIR__ .'/extremeiceland.is/mysql-TEST_6_orig.php';
//require_once __DIR__ .'/extremeiceland.is/mysql-TEST_6_var1.php';
//require_once __DIR__ .'/extremeiceland.is/mysql-TEST_7_orig.php';
//require_once __DIR__ .'/extremeiceland.is/mysql-TEST_7_var1.php';
//require_once __DIR__ .'/extremeiceland.is/mysql-TEST_8_orig.php';
//require_once __DIR__ .'/extremeiceland.is/mysql-TEST_8_var1.php';
//require_once __DIR__ .'/extremeiceland.is/mysql-TEST_9_orig.php';
//require_once __DIR__ .'/extremeiceland.is/mysql-TEST_9_var1.php';
//require_once __DIR__ .'/extremeiceland.is/mysql-TEST_10_orig.php';
//require_once __DIR__ .'/extremeiceland.is/mysql-TEST_10_var1.php';
//require_once __DIR__ .'/extremeiceland.is/mysql-TEST_11_orig.php';
//require_once __DIR__ .'/extremeiceland.is/mysql-TEST_11_var1.php';
//require_once __DIR__ .'/extremeiceland.is/mysql-TEST_12_orig.php';
//require_once __DIR__ .'/extremeiceland.is/mysql-TEST_12_var1.php';
//require_once __DIR__ .'/extremeiceland.is/mysql-TEST_aa_orig.php';
//require_once __DIR__ .'/extremeiceland.is/mysql-TEST_aa_var1.php';
require_once __DIR__ .'/extremeiceland.is/mysql-TEST_allSessions.php';

//TELIA ESHOP
require_once __DIR__ .'/telia.lt_eshop/mysql-config.php';
//require_once __DIR__ .'/telia.lt_eshop/mysql-TEST_TeliaI1H5TDM_orig.php';
//require_once __DIR__ .'/telia.lt_eshop/mysql-TEST_TeliaI1H5TDM_var1.php';
//require_once __DIR__ .'/telia.lt_eshop/mysql-TEST_TeliaI1H20TDM_orig.php';
//require_once __DIR__ .'/telia.lt_eshop/mysql-TEST_TeliaI1H20TDM_var1.php';
//require_once __DIR__ .'/telia.lt_eshop/mysql-TEST_TeliaI2H29TDM_orig.php';
//require_once __DIR__ .'/telia.lt_eshop/mysql-TEST_TeliaI2H29TDM_var1.php';
//require_once __DIR__ .'/telia.lt_eshop/mysql-TEST_TeliaI2H25TDM_orig.php';
//require_once __DIR__ .'/telia.lt_eshop/mysql-TEST_TeliaI2H25TDM_var1.php';
//require_once __DIR__ .'/telia.lt_eshop/mysql-TEST_TeliaI2H26TDM_orig.php';
//require_once __DIR__ .'/telia.lt_eshop/mysql-TEST_TeliaI2H26TDM_var1.php';
//require_once __DIR__ .'/telia.lt_eshop/mysql-TEST_TeliaI2H13TDM_orig.php';
//require_once __DIR__ .'/telia.lt_eshop/mysql-TEST_TeliaI2H13TDM_var1.php';
//require_once __DIR__ .'/telia.lt_eshop/mysql-TEST_TeliaI2H27TDM_orig.php';
//require_once __DIR__ .'/telia.lt_eshop/mysql-TEST_TeliaI2H27TDM_var1.php';
// require_once __DIR__ .'/telia.lt_eshop/mysql-TEST_TeliaI3H1TDM_orig.php';
// require_once __DIR__ .'/telia.lt_eshop/mysql-TEST_TeliaI3H1TDM_var1.php';
// require_once __DIR__ .'/telia.lt_eshop/mysql-TEST_TeliaI3H2TDM_orig.php';
// require_once __DIR__ .'/telia.lt_eshop/mysql-TEST_TeliaI3H2TDM_var1.php';
// require_once __DIR__ .'/telia.lt_eshop/mysql-TEST_TeliaI3H5TDM_orig.php';
// require_once __DIR__ .'/telia.lt_eshop/mysql-TEST_TeliaI3H5TDM_var1.php';
// require_once __DIR__ .'/telia.lt_eshop/mysql-TEST_TeliaI3H6TDM_orig.php';
// require_once __DIR__ .'/telia.lt_eshop/mysql-TEST_TeliaI3H6TDM_var1.php';
require_once __DIR__ .'/telia.lt_eshop/mysql-TEST_allSessions.php';

//TELIA.lt
require_once __DIR__ .'/telia.lt/mysql-config.php';
//require_once __DIR__ .'/telia.lt/mysql-TEST_TeliaI2H24TDM_orig.php';
//require_once __DIR__ .'/telia.lt/mysql-TEST_TeliaI2H24TDM_var1.php';

//EUROVAISTINE.LT
require_once __DIR__ .'/eurovaistine.lt/mysql-config.php';
//require_once __DIR__ .'/eurovaistine.lt/mysql-TEST_EuroI1H8TDM_orig.php';
//require_once __DIR__ .'/eurovaistine.lt/mysql-TEST_EuroI1H8TDM_var1.php';
//require_once __DIR__ .'/eurovaistine.lt/mysql-TEST_EuroI1H14TDM_orig.php';
//require_once __DIR__ .'/eurovaistine.lt/mysql-TEST_EuroI1H14TDM_var1.php';
//require_once __DIR__ .'/eurovaistine.lt/mysql-TEST_EuroI1H20TD_orig.php';
//require_once __DIR__ .'/eurovaistine.lt/mysql-TEST_EuroI1H20TD_var1.php';
//require_once __DIR__ .'/eurovaistine.lt/mysql-TEST_EuroI1H23TDM_orig.php';
//require_once __DIR__ .'/eurovaistine.lt/mysql-TEST_EuroI1H23TDM_var1.php';
//require_once __DIR__ .'/eurovaistine.lt/mysql-TEST_EuroI1H26TM_orig.php';
//require_once __DIR__ .'/eurovaistine.lt/mysql-TEST_EuroI1H26TM_var1.php';
//require_once __DIR__ .'/eurovaistine.lt/mysql-TEST_EuroI1H17TDM_orig.php';
//require_once __DIR__ .'/eurovaistine.lt/mysql-TEST_EuroI1H17TDM_var1.php';
//require_once __DIR__ .'/eurovaistine.lt/mysql-TEST_EuroI1H18TD_orig.php';
//require_once __DIR__ .'/eurovaistine.lt/mysql-TEST_EuroI1H18TD_var1.php';
//require_once __DIR__ .'/eurovaistine.lt/mysql-TEST_EuroI1H11TM_orig.php';
//require_once __DIR__ .'/eurovaistine.lt/mysql-TEST_EuroI1H11TM_var1.php';
//require_once __DIR__ .'/eurovaistine.lt/mysql-TEST_EuroI1H2TDM_orig.php';
//require_once __DIR__ .'/eurovaistine.lt/mysql-TEST_EuroI1H2TDM_var1.php';
//require_once __DIR__ .'/eurovaistine.lt/mysql-TEST_EuroI1H15TDM_orig.php';
//require_once __DIR__ .'/eurovaistine.lt/mysql-TEST_EuroI1H15TDM_var1.php';
//require_once __DIR__ .'/eurovaistine.lt/mysql-TEST_EuroI1H22TD_orig.php';
//require_once __DIR__ .'/eurovaistine.lt/mysql-TEST_EuroI1H22TD_var1.php';
//require_once __DIR__ .'/eurovaistine.lt/mysql-TEST_EuroI1H12TDM_orig.php';
//require_once __DIR__ .'/eurovaistine.lt/mysql-TEST_EuroI1H12TDM_var1.php';
//require_once __DIR__ .'/eurovaistine.lt/mysql-TEST_EuroI2H4TD_orig.php';
//require_once __DIR__ .'/eurovaistine.lt/mysql-TEST_EuroI2H4TD_var1.php';
//require_once __DIR__ .'/eurovaistine.lt/mysql-TEST_EuroI2H6TM_orig.php';
//require_once __DIR__ .'/eurovaistine.lt/mysql-TEST_EuroI2H6TM_var1.php';
//require_once __DIR__ .'/eurovaistine.lt/mysql-TEST_EuroI2H8TDM_orig.php';
//require_once __DIR__ .'/eurovaistine.lt/mysql-TEST_EuroI2H8TDM_var1.php';
//require_once __DIR__ .'/eurovaistine.lt/mysql-TEST_EuroI2H9TD_orig.php';
//require_once __DIR__ .'/eurovaistine.lt/mysql-TEST_EuroI2H9TD_var1.php';
//require_once __DIR__ .'/eurovaistine.lt/mysql-TEST_EuroI2H10TDM_orig.php';
//require_once __DIR__ .'/eurovaistine.lt/mysql-TEST_EuroI2H10TDM_var1.php';
//require_once __DIR__ .'/eurovaistine.lt/mysql-TEST_EuroI2H12TD_orig.php';
//require_once __DIR__ .'/eurovaistine.lt/mysql-TEST_EuroI2H12TD_var1.php';
//require_once __DIR__ .'/eurovaistine.lt/mysql-TEST_EuroI2H13TD_orig.php';
//require_once __DIR__ .'/eurovaistine.lt/mysql-TEST_EuroI2H13TD_var1.php';
//require_once __DIR__ .'/eurovaistine.lt/mysql-TEST_EuroI2H14TDM_orig.php';
//require_once __DIR__ .'/eurovaistine.lt/mysql-TEST_EuroI2H14TDM_var1.php';
//require_once __DIR__ .'/eurovaistine.lt/mysql-TEST_EuroI2H15TDM_orig.php';
//require_once __DIR__ .'/eurovaistine.lt/mysql-TEST_EuroI2H15TDM_var1.php';
//require_once __DIR__ .'/eurovaistine.lt/mysql-TEST_EuroI2H16TD_orig.php';
//require_once __DIR__ .'/eurovaistine.lt/mysql-TEST_EuroI2H16TD_var1.php';
//require_once __DIR__ .'/eurovaistine.lt/mysql-TEST_EuroI2H18TDM_orig.php';
//require_once __DIR__ .'/eurovaistine.lt/mysql-TEST_EuroI2H18TDM_var1.php';
//require_once __DIR__ .'/eurovaistine.lt/mysql-TEST_EuroI2H19TDM_orig.php';
//require_once __DIR__ .'/eurovaistine.lt/mysql-TEST_EuroI2H19TDM_var1.php';
//require_once __DIR__ .'/eurovaistine.lt/mysql-TEST_EuroI2H20TD_orig.php';
//require_once __DIR__ .'/eurovaistine.lt/mysql-TEST_EuroI2H20TD_var1.php';
// require_once __DIR__ .'/eurovaistine.lt/mysql-TEST_EuroI3H1TDM_orig.php';
// require_once __DIR__ .'/eurovaistine.lt/mysql-TEST_EuroI3H1TDM_var1.php';
require_once __DIR__ .'/eurovaistine.lt/mysql-TEST_allSessions.php';

//GINTARINE.LT
require_once __DIR__ .'/gintarine.lt/mysql-config.php';
//require_once __DIR__ .'/gintarine.lt/mysql-TEST_aa_orig.php';
//require_once __DIR__ .'/gintarine.lt/mysql-TEST_aa_var1.php';
//require_once __DIR__ .'/gintarine.lt/mysql-TEST_GintI1H4TDM_orig.php';
//require_once __DIR__ .'/gintarine.lt/mysql-TEST_GintI1H4TDM_var1.php';
//require_once __DIR__ .'/gintarine.lt/mysql-TEST_GintI1H5TDM_orig.php';
//require_once __DIR__ .'/gintarine.lt/mysql-TEST_GintI1H5TDM_var1.php';
//require_once __DIR__ .'/gintarine.lt/mysql-TEST_GintI1H9TD_orig.php';
//require_once __DIR__ .'/gintarine.lt/mysql-TEST_GintI1H9TD_var1.php';
//require_once __DIR__ .'/gintarine.lt/mysql-TEST_GintI1H10TD_orig.php';
//require_once __DIR__ .'/gintarine.lt/mysql-TEST_GintI1H10TD_var1.php';
//require_once __DIR__ .'/gintarine.lt/mysql-TEST_GintI1H17TDM_orig.php';
//require_once __DIR__ .'/gintarine.lt/mysql-TEST_GintI1H17TDM_var1.php';

//SKYTECH.LT
require_once __DIR__ .'/skytech.lt/mysql-config.php';
//require_once __DIR__ .'/skytech.lt/mysql-TEST_SkyI1H1TDM_orig.php';
//require_once __DIR__ .'/skytech.lt/mysql-TEST_SkyI1H1TDM_var1.php';
//require_once __DIR__ .'/skytech.lt/mysql-TEST_SkyI1H2TDM_orig.php';
//require_once __DIR__ .'/skytech.lt/mysql-TEST_SkyI1H2TDM_var1.php';
//require_once __DIR__ .'/skytech.lt/mysql-TEST_SkyI1H3TDM_orig.php';
//require_once __DIR__ .'/skytech.lt/mysql-TEST_SkyI1H3TDM_var1.php';
//require_once __DIR__ .'/skytech.lt/mysql-TEST_SkyI1H4TDM_orig.php';
//require_once __DIR__ .'/skytech.lt/mysql-TEST_SkyI1H4TDM_var1.php';
//require_once __DIR__ .'/skytech.lt/mysql-TEST_SkyI1H5TDM_orig.php';
//require_once __DIR__ .'/skytech.lt/mysql-TEST_SkyI1H5TDM_var1.php';
//require_once __DIR__ .'/skytech.lt/mysql-TEST_SkyI1H6TDM_orig.php';
//require_once __DIR__ .'/skytech.lt/mysql-TEST_SkyI1H6TDM_var1.php';
//require_once __DIR__ .'/skytech.lt/mysql-TEST_SkyI1H8TM_orig.php';
//require_once __DIR__ .'/skytech.lt/mysql-TEST_SkyI1H8TM_var1.php';
//require_once __DIR__ .'/skytech.lt/mysql-TEST_SkyI1H9TDM_orig.php';
//require_once __DIR__ .'/skytech.lt/mysql-TEST_SkyI1H9TDM_var1.php';
//require_once __DIR__ .'/skytech.lt/mysql-TEST_SkyI1H10TDM_orig.php';
//require_once __DIR__ .'/skytech.lt/mysql-TEST_SkyI1H10TDM_var1.php';
//require_once __DIR__ .'/skytech.lt/mysql-TEST_SkyI1H11TDM_orig.php';
//require_once __DIR__ .'/skytech.lt/mysql-TEST_SkyI1H11TDM_var1.php';
//require_once __DIR__ .'/skytech.lt/mysql-TEST_SkyI1H12TDM_orig.php';
//require_once __DIR__ .'/skytech.lt/mysql-TEST_SkyI1H12TDM_var1.php';
//require_once __DIR__ .'/skytech.lt/mysql-TEST_SkyI1H13TDM_orig.php';
//require_once __DIR__ .'/skytech.lt/mysql-TEST_SkyI1H13TDM_var1.php';
//require_once __DIR__ .'/skytech.lt/mysql-TEST_SkyI1H14TD_orig.php';
//require_once __DIR__ .'/skytech.lt/mysql-TEST_SkyI1H14TD_var1.php';
//require_once __DIR__ .'/skytech.lt/mysql-TEST_SkyI1H15TDM_orig.php';
//require_once __DIR__ .'/skytech.lt/mysql-TEST_SkyI1H15TDM_var1.php';
//require_once __DIR__ .'/skytech.lt/mysql-TEST_SkyI1H16TDM_orig.php';
//require_once __DIR__ .'/skytech.lt/mysql-TEST_SkyI1H16TDM_var1.php';
//require_once __DIR__ .'/skytech.lt/mysql-TEST_SkyI1H17TDM_orig.php';
//require_once __DIR__ .'/skytech.lt/mysql-TEST_SkyI1H17TDM_var1.php';
//require_once __DIR__ .'/skytech.lt/mysql-TEST_SkyI1H18TDM_orig.php';
//require_once __DIR__ .'/skytech.lt/mysql-TEST_SkyI1H18TDM_var1.php';
//require_once __DIR__ .'/skytech.lt/mysql-TEST_SkyI1H19TDM_orig.php';
//require_once __DIR__ .'/skytech.lt/mysql-TEST_SkyI1H19TDM_var1.php';
//require_once __DIR__ .'/skytech.lt/mysql-TEST_SkyI1R1TDM_orig.php';
//require_once __DIR__ .'/skytech.lt/mysql-TEST_SkyI1R1TDM_var1.php';
//require_once __DIR__ .'/skytech.lt/mysql-TEST_SkyI1R2TDM_orig.php';
//require_once __DIR__ .'/skytech.lt/mysql-TEST_SkyI1R2TDM_var1.php';
require_once __DIR__ .'/skytech.lt/mysql-TEST_allSessions.php';

//PERLAS.LT
//require_once __DIR__ .'/perlas.lt/mysql-config.php';
//require_once __DIR__ .'/perlas.lt/mysql-TEST_PerlasI1H1TD_orig.php';
//require_once __DIR__ .'/perlas.lt/mysql-TEST_PerlasI1H1TD_var1.php';
//require_once __DIR__ .'/perlas.lt/mysql-TEST_PerlasI1H2TM_orig.php';
//require_once __DIR__ .'/perlas.lt/mysql-TEST_PerlasI1H2TM_var1.php';
//require_once __DIR__ .'/perlas.lt/mysql-TEST_PerlasI1H3TD_orig.php';
//require_once __DIR__ .'/perlas.lt/mysql-TEST_PerlasI1H3TD_var1.php';
//require_once __DIR__ .'/perlas.lt/mysql-TEST_PerlasI1H4TM_orig.php';
//require_once __DIR__ .'/perlas.lt/mysql-TEST_PerlasI1H4TM_var1.php';
//require_once __DIR__ .'/perlas.lt/mysql-TEST_PerlasI1H5TM_orig.php';
//require_once __DIR__ .'/perlas.lt/mysql-TEST_PerlasI1H5TM_var1.php';
//require_once __DIR__ .'/perlas.lt/mysql-TEST_allSessions.php';

//IKEA.LT
require_once __DIR__ .'/ikea.lt/mysql-config.php';
//require_once __DIR__ .'/ikea.lt/mysql-TEST_IKEAI1H1TD_orig.php';
//require_once __DIR__ .'/ikea.lt/mysql-TEST_IKEAI1H1TD_var1.php';
//require_once __DIR__ .'/ikea.lt/mysql-TEST_IKEAI1H3TDM_orig.php';
//require_once __DIR__ .'/ikea.lt/mysql-TEST_IKEAI1H3TDM_var1.php';
//require_once __DIR__ .'/ikea.lt/mysql-TEST_IKEAI1H4TDM_orig.php';
//require_once __DIR__ .'/ikea.lt/mysql-TEST_IKEAI1H4TDM_var1.php';
//require_once __DIR__ .'/ikea.lt/mysql-TEST_IKEAI1H5TDM_orig.php';
//require_once __DIR__ .'/ikea.lt/mysql-TEST_IKEAI1H5TDM_var1.php';
//require_once __DIR__ .'/ikea.lt/mysql-TEST_IKEAI1H7TDM_orig.php';
//require_once __DIR__ .'/ikea.lt/mysql-TEST_IKEAI1H7TDM_var1.php';
//require_once __DIR__ .'/ikea.lt/mysql-TEST_IKEAI1H8TDM_orig.php';
//require_once __DIR__ .'/ikea.lt/mysql-TEST_IKEAI1H8TDM_var1.php';
//require_once __DIR__ .'/ikea.lt/mysql-TEST_IKEAI1H9TM_orig.php';
//require_once __DIR__ .'/ikea.lt/mysql-TEST_IKEAI1H9TM_var1.php';
//require_once __DIR__ .'/ikea.lt/mysql-TEST_IKEAI1H10TDM_orig.php';
//require_once __DIR__ .'/ikea.lt/mysql-TEST_IKEAI1H10TDM_var1.php';
//require_once __DIR__ .'/ikea.lt/mysql-TEST_IKEAI1H11TDM_orig.php';
//require_once __DIR__ .'/ikea.lt/mysql-TEST_IKEAI1H11TDM_var1.php';
//require_once __DIR__ .'/ikea.lt/mysql-TEST_IKEAI1H11TDM_V2_orig.php';
//require_once __DIR__ .'/ikea.lt/mysql-TEST_IKEAI1H11TDM_V2_var1.php';
//require_once __DIR__ .'/ikea.lt/mysql-TEST_IKEAI1H12TDM_orig.php';
//require_once __DIR__ .'/ikea.lt/mysql-TEST_IKEAI1H12TDM_var1.php';
//require_once __DIR__ .'/ikea.lt/mysql-TEST_IKEAI1H13TDM_orig.php';
//require_once __DIR__ .'/ikea.lt/mysql-TEST_IKEAI1H13TDM_var1.php';
//require_once __DIR__ .'/ikea.lt/mysql-TEST_IKEAI1H14TDM_orig.php';
//require_once __DIR__ .'/ikea.lt/mysql-TEST_IKEAI1H14TDM_var1.php';
//require_once __DIR__ .'/ikea.lt/mysql-TEST_IKEAI1H15TDM_orig.php';
//require_once __DIR__ .'/ikea.lt/mysql-TEST_IKEAI1H15TDM_var1.php';
//require_once __DIR__ .'/ikea.lt/mysql-TEST_IKEAI1H17TDM_orig.php';
//require_once __DIR__ .'/ikea.lt/mysql-TEST_IKEAI1H17TDM_var1.php';
//require_once __DIR__ .'/ikea.lt/mysql-TEST_IKEAI1H19TDM_orig.php';
//require_once __DIR__ .'/ikea.lt/mysql-TEST_IKEAI1H19TDM_var1.php';
require_once __DIR__ .'/ikea.lt/mysql-TEST_allSessions.php';

//TOPOCENTRAS.LT
require_once __DIR__ .'/topocentras.lt/mysql-config.php';
//require_once __DIR__ .'/topocentras.lt/mysql-TEST_TopoI1H11TDM_orig.php';
//require_once __DIR__ .'/topocentras.lt/mysql-TEST_TopoI1H11TDM_var1.php';
//require_once __DIR__ .'/topocentras.lt/mysql-TEST_TopoI1H13TDM_orig.php';
//require_once __DIR__ .'/topocentras.lt/mysql-TEST_TopoI1H13TDM_var1.php';
//require_once __DIR__ .'/topocentras.lt/mysql-TEST_TopoI1H21TDM_orig.php';
//require_once __DIR__ .'/topocentras.lt/mysql-TEST_TopoI1H21TDM_var1.php';
// require_once __DIR__ .'/topocentras.lt/mysql-TEST_TopoI1H14TDM_orig.php';
// require_once __DIR__ .'/topocentras.lt/mysql-TEST_TopoI1H14TDM_var1.php';
// require_once __DIR__ .'/topocentras.lt/mysql-TEST_TopoI1H12TDM_orig.php';
// require_once __DIR__ .'/topocentras.lt/mysql-TEST_TopoI1H12TDM_var1.php';
// require_once __DIR__ .'/topocentras.lt/mysql-TEST_TopoI1H15TDM_orig.php';
// require_once __DIR__ .'/topocentras.lt/mysql-TEST_TopoI1H15TDM_var1.php';
//require_once __DIR__ .'/topocentras.lt/mysql-TEST_TopoI1H17TM_orig.php';
//require_once __DIR__ .'/topocentras.lt/mysql-TEST_TopoI1H17TM_var1.php';
//require_once __DIR__ .'/topocentras.lt/mysql-TEST_TopoI1H18TDM_orig.php';
//require_once __DIR__ .'/topocentras.lt/mysql-TEST_TopoI1H18TDM_var1.php';
// require_once __DIR__ .'/topocentras.lt/mysql-TEST_TopoI1H5TDM_orig.php';
// require_once __DIR__ .'/topocentras.lt/mysql-TEST_TopoI1H5TDM_var1.php';
// require_once __DIR__ .'/topocentras.lt/mysql-TEST_TopoI2H1TDM_orig.php';
// require_once __DIR__ .'/topocentras.lt/mysql-TEST_TopoI2H1TDM_var1.php';
// require_once __DIR__ .'/topocentras.lt/mysql-TEST_TopoI2H3TDM_orig.php';
// require_once __DIR__ .'/topocentras.lt/mysql-TEST_TopoI2H3TDM_var1.php';
// require_once __DIR__ .'/topocentras.lt/mysql-TEST_TopoI1H5TDM_V2_orig.php';
// require_once __DIR__ .'/topocentras.lt/mysql-TEST_TopoI1H5TDM_V2_var1.php';
// require_once __DIR__ .'/topocentras.lt/mysql-TEST_TopoI2H1TDM_V2_orig.php';
// require_once __DIR__ .'/topocentras.lt/mysql-TEST_TopoI2H1TDM_V2_var1.php';
// require_once __DIR__ .'/topocentras.lt/mysql-TEST_TopoI2H3TDM_V2_orig.php';
// require_once __DIR__ .'/topocentras.lt/mysql-TEST_TopoI2H3TDM_V2_var1.php';
// require_once __DIR__ .'/topocentras.lt/mysql-TEST_TopoI3H2TDM_orig.php';
// require_once __DIR__ .'/topocentras.lt/mysql-TEST_TopoI3H2TDM_var1.php';
// require_once __DIR__ .'/topocentras.lt/mysql-TEST_TopoI3H3TD_orig.php';
// require_once __DIR__ .'/topocentras.lt/mysql-TEST_TopoI3H3TD_var1.php';
require_once __DIR__ .'/topocentras.lt/mysql-TEST_TopoI3H6TM_orig.php';
require_once __DIR__ .'/topocentras.lt/mysql-TEST_TopoI3H6TM_var1.php';
require_once __DIR__ .'/topocentras.lt/mysql-TEST_TopoI3H1TDM_V2_orig.php';
require_once __DIR__ .'/topocentras.lt/mysql-TEST_TopoI3H1TDM_V2_var1.php';
require_once __DIR__ .'/topocentras.lt/mysql-TEST_TopoI4H1TD_orig.php';
require_once __DIR__ .'/topocentras.lt/mysql-TEST_TopoI4H1TD_var1.php';
require_once __DIR__ .'/topocentras.lt/mysql-TEST_TopoI4H3TDM_V2_orig.php';
require_once __DIR__ .'/topocentras.lt/mysql-TEST_TopoI4H3TDM_V2_var1.php';
require_once __DIR__ .'/topocentras.lt/mysql-TEST_allSessions.php';


//LD.LT
require_once __DIR__ .'/ld.lt/mysql-config.php';
// require_once __DIR__ .'/ld.lt/mysql-TEST_LDI1H4TDM_orig.php';
// require_once __DIR__ .'/ld.lt/mysql-TEST_LDI1H4TDM_var1.php';
// require_once __DIR__ .'/ld.lt/mysql-TEST_LDI1H13TDM_orig.php';
// require_once __DIR__ .'/ld.lt/mysql-TEST_LDI1H13TDM_var1.php';
// require_once __DIR__ .'/ld.lt/mysql-TEST_LDI1H14TD_orig.php';
// require_once __DIR__ .'/ld.lt/mysql-TEST_LDI1H14TD_var1.php';
// require_once __DIR__ .'/ld.lt/mysql-TEST_LDI1H15TDM_orig.php';
// require_once __DIR__ .'/ld.lt/mysql-TEST_LDI1H15TDM_var1.php';
// require_once __DIR__ .'/ld.lt/mysql-TEST_LDI1H13TDM_V2_orig.php';
// require_once __DIR__ .'/ld.lt/mysql-TEST_LDI1H13TDM_V2_var1.php';
// require_once __DIR__ .'/ld.lt/mysql-TEST_LDI1H14TD_V2_orig.php';
// require_once __DIR__ .'/ld.lt/mysql-TEST_LDI1H14TD_V2_var1.php';
// require_once __DIR__ .'/ld.lt/mysql-TEST_LDI1H15TDM_V2_orig.php';
// require_once __DIR__ .'/ld.lt/mysql-TEST_LDI1H15TDM_V2_var1.php';
require_once __DIR__ .'/ld.lt/mysql-TEST_LDI1H7TDM_orig.php';
require_once __DIR__ .'/ld.lt/mysql-TEST_LDI1H7TDM_var1.php';
// require_once __DIR__ .'/ld.lt/mysql-TEST_LDI1H12TDM_orig.php';
// require_once __DIR__ .'/ld.lt/mysql-TEST_LDI1H12TDM_var1.php';
require_once __DIR__ .'/ld.lt/mysql-TEST_LDI1H2TDM_orig.php';
require_once __DIR__ .'/ld.lt/mysql-TEST_LDI1H2TDM_var1.php';
require_once __DIR__ .'/ld.lt/mysql-TEST_LDI1H4TDM_V2_orig.php';
require_once __DIR__ .'/ld.lt/mysql-TEST_LDI1H4TDM_V2_var1.php';
require_once __DIR__ .'/ld.lt/mysql-TEST_allSessions.php';

//FACTCOOL.COM
require_once __DIR__ .'/factcool.com/mysql-config.php';
// require_once __DIR__ .'/factcool.com/mysql-TEST_FcoolI1H12TDM_orig.php';
// require_once __DIR__ .'/factcool.com/mysql-TEST_FcoolI1H12TDM_var1.php';
// require_once __DIR__ .'/factcool.com/mysql-TEST_FcoolI1H17TDM_orig.php';
// require_once __DIR__ .'/factcool.com/mysql-TEST_FcoolI1H17TDM_var1.php';
// require_once __DIR__ .'/factcool.com/mysql-TEST_FcoolI1H6TDM_orig.php';
// require_once __DIR__ .'/factcool.com/mysql-TEST_FcoolI1H6TDM_var1.php';
// require_once __DIR__ .'/factcool.com/mysql-TEST_FcoolI1H7TDM_orig.php';
// require_once __DIR__ .'/factcool.com/mysql-TEST_FcoolI1H7TDM_var1.php';
// require_once __DIR__ .'/factcool.com/mysql-TEST_FcoolI1H3TD_orig.php';
// require_once __DIR__ .'/factcool.com/mysql-TEST_FcoolI1H3TD_var1.php';
// require_once __DIR__ .'/factcool.com/mysql-TEST_FcoolI1H9TM_V2_orig.php';
// require_once __DIR__ .'/factcool.com/mysql-TEST_FcoolI1H9TM_V2_var1.php';
// require_once __DIR__ .'/factcool.com/mysql-TEST_FcoolI1H13TDM_orig.php';
// require_once __DIR__ .'/factcool.com/mysql-TEST_FcoolI1H13TDM_var1.php';
// require_once __DIR__ .'/factcool.com/mysql-TEST_FcoolI1H13TDM_V2_orig.php';
// require_once __DIR__ .'/factcool.com/mysql-TEST_FcoolI1H13TDM_V2_var1.php';
// require_once __DIR__ .'/factcool.com/mysql-TEST_FcoolI1H8TD_V2_orig.php';
// require_once __DIR__ .'/factcool.com/mysql-TEST_FcoolI1H8TD_V2_var1.php';
// require_once __DIR__ .'/factcool.com/mysql-TEST_FcoolI1H18TDM_orig.php';
// require_once __DIR__ .'/factcool.com/mysql-TEST_FcoolI1H18TDM_var1.php';
// require_once __DIR__ .'/factcool.com/mysql-TEST_FcoolI1H10TD_orig.php';
// require_once __DIR__ .'/factcool.com/mysql-TEST_FcoolI1H10TD_var1.php';
require_once __DIR__ .'/factcool.com/mysql-TEST_allSessions.php';

//RRR.COM
require_once __DIR__ .'/rrr.lt/mysql-config.php';
require_once __DIR__ .'/rrr.lt/mysql-TEST_RRRI1H11TM_orig.php';
require_once __DIR__ .'/rrr.lt/mysql-TEST_RRRI1H11TM_var1.php';
require_once __DIR__ .'/rrr.lt/mysql-TEST_RRRI1H13TDM_V2_orig.php';
require_once __DIR__ .'/rrr.lt/mysql-TEST_RRRI1H13TDM_V2_var1.php';
require_once __DIR__ .'/rrr.lt/mysql-TEST_allSessions.php';


$defaultAdminEmailAddress = 'dmitrij@seopro.lt';
$headers  = 'MIME-Version: 1.0' . "\r\n";
$headers .= 'Content-type: text/html; charset=UTF-8' . "\r\n";
$headers .= 'From: '.$defaultAdminEmailAddress . "\r\n" .
	'Reply-To: '.$defaultAdminEmailAddress . "\r\n" .
	'X-Mailer: PHP/' . phpversion();
$userEmail = 'ALL tables updated';		
mail($defaultAdminEmailAddress, '=?utf-8?B?'.base64_encode('Database update').'?=', $userEmail, $headers);

require_once __DIR__ . '/halfTest.php';
//}
?>